version: '3.8'
services:
  ollama:
      image: ollama/ollama:latest
      platform: linux/arm64  # Required for Mac M1/M2
      ports:
        - 11435:11435
      volumes:
        - .:/code
        - ./ollama/ollama:/root/.ollama
      container_name: ollama
      pull_policy: always
      tty: true
      restart: always
      environment:
        - OLLAMA_KEEP_ALIVE=24h
        - OLLAMA_HOST=0.0.0.0
      networks:
        - ollama-docker

  fastapi:
    build: ./fastapi  # Path to your FastAPI app
    container_name: fastapi-server
    ports:
      - "8000:8000"  # FastAPI app exposed to port 8000
    depends_on:
      - ollama  # Wait for Ollama container to be ready
    networks:
      - ollama-docker
      
networks:
  ollama-docker:
    external: false